// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfRcqVP5oTWjJ2DigXXBshxINUNebv8bg',
    appId: '1:1092864783324:web:31f6e12b8023dedf185519',
    messagingSenderId: '1092864783324',
    projectId: 'wedding-app-f3b7d',
    authDomain: 'wedding-app-f3b7d.firebaseapp.com',
    storageBucket: 'wedding-app-f3b7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGat9YLpZj5RytfuMRnrFQ2wmkmD9T07Y',
    appId: '1:1092864783324:android:5ee5abadc1c1198e185519',
    messagingSenderId: '1092864783324',
    projectId: 'wedding-app-f3b7d',
    storageBucket: 'wedding-app-f3b7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpkt4bU0IwZtl2PcEQm-hT7Y--5QdxItA',
    appId: '1:1092864783324:ios:008056f1a7009f34185519',
    messagingSenderId: '1092864783324',
    projectId: 'wedding-app-f3b7d',
    storageBucket: 'wedding-app-f3b7d.firebasestorage.app',
    iosBundleId: 'com.example.edtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpkt4bU0IwZtl2PcEQm-hT7Y--5QdxItA',
    appId: '1:1092864783324:ios:008056f1a7009f34185519',
    messagingSenderId: '1092864783324',
    projectId: 'wedding-app-f3b7d',
    storageBucket: 'wedding-app-f3b7d.firebasestorage.app',
    iosBundleId: 'com.example.edtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfRcqVP5oTWjJ2DigXXBshxINUNebv8bg',
    appId: '1:1092864783324:web:5dd3bd6254ce8e30185519',
    messagingSenderId: '1092864783324',
    projectId: 'wedding-app-f3b7d',
    authDomain: 'wedding-app-f3b7d.firebaseapp.com',
    storageBucket: 'wedding-app-f3b7d.firebasestorage.app',
  );

}